version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - back
networks:
  back: